version: '3.9'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "28017:27017"
    volumes:
      - mongo_db:/data/db
  token:
    build: .
    volumes:
      - ./database/mongoDB:/database/mongoDB
    depends_on:
      - mongodb

volumes:
  mongo_db: