version: '3.9'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "28017:27017"
    volumes:
      - mongo_db:/data/db
  token:
    build: ..
    volumes:
       - ./:/personal_finance_tracker

    depends_on:
      - mongodb

volumes:
  mongo_db: